"""add order_total to carts

Revision ID: 25a6f56be822
Revises: a4a81b0db67d
Create Date: 2023-04-20 09:49:21.260142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a6f56be822'
down_revision = 'a4a81b0db67d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_total', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('order_total')

    # ### end Alembic commands ###
