"""add user_id to carts table

Revision ID: 99e19ff4b0ad
Revises: 8b0978a00bf3
Create Date: 2023-04-19 14:40:19.364845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e19ff4b0ad'
down_revision = '8b0978a00bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
